#!/bin/bash

AMASTER=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $5}'`
ASTAT=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $6}'`
ICON=""

if [[ $ASTAT = "on" ]]; then
    ICON="spkr_01.xbm"
    PERCBAR=`echo -e "$AMASTER"\
        | gdbar -bg "#393939" -fg "#d6d6d6" -h 3 -w 60`
else
    ICON="spkr_02.xbm"
    PERCBAR=`echo 0\
        | gdbar -bg "#393939" -fg "#d6d6d6" -h 3 -w 60`
fi

ICON='^i(/home/a$USER/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
echo "$ICON $PERCBAR"
